{% set name = "opentelemetry-instrumentation-sqlalchemy" %}
{% set version = "0.54b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_sqlalchemy-{{ version }}.tar.gz
  sha256: 97839acf1c9b96ded857fca57a09b86a56cf8d9eb6d706b7ceaee9352a460e03

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.54b1
    - opentelemetry-semantic-conventions ==0.54b1
    - packaging >=21.0
    - wrapt >=1.11.2
    # - sqlalchemy 
    # - pytest 
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-sqlalchemy 
    # - sqlalchemy 
    # - pytest 
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-sqlalchemy 
    # - sqlalchemy 
    # - pytest 
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-sqlalchemy 
    # - sqlalchemy 
    # - pytest 
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-sqlalchemy 
    # - sqlalchemy 
    # - pytest 
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-sqlalchemy 
    # - sqlalchemy 
    # - pytest 
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-sqlalchemy 
    # - sqlalchemy 
    # - pytest 
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-sqlalchemy 
    # - sqlalchemy 
    # - pytest 
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-sqlalchemy 
    # - sqlalchemy 
    # - sqlalchemy 
    # - sqlalchemy 
    # - sqlalchemy 
    # - sqlalchemy 
    # - sqlalchemy <2.1.0,>=1.0.0
    # - sqlalchemy <2.1.0,>=1.0.0
    # - sqlalchemy <2.1.0,>=1.0.0
    # - sqlalchemy <2.1.0,>=1.0.0
    # - sqlalchemy <2.1.0,>=1.0.0
    # - sqlalchemy <2.1.0,>=1.0.0
    # - sqlalchemy <2.1.0,>=1.0.0
    # - sqlalchemy <2.1.0,>=1.0.0
    # - sqlalchemy <2.1.0,>=1.0.0
    # - sqlalchemy <2.1.0,>=1.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-sqlalchemy
  summary: OpenTelemetry SQLAlchemy instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
